/**
 * `@xano-sdk/zod/plugin` — the toolchain module the SDK loads.
 *
 * The ONLY file in this repo that faces `@xano/sdk`, and only through
 * `import type`: the contract's shapes are erased at build time, so the built
 * plugin imports nothing from the peer at runtime.
 *
 * The SDK finds it through this package's manifest:
 *
 *     "xanosdk": { "kind": "toolchain", "plugin": "./dist/plugin.js" }
 */
import type { ProjectContributions, ToolchainPlugin } from "@xano/sdk/plugin";

const PACKAGE_NAME = "@xano-sdk/zod";

// ─────────────────────────────────────────────────────────────────────────────
// The peer range
// ─────────────────────────────────────────────────────────────────────────────

/**
 * The `@xano/sdk` versions this module is correct against, matching the
 * `peerDependencies` range in `package.json`. The test suite asserts the two
 * agree.
 *
 * The floor is the first SDK that lets a toolchain module add a section to
 * `routes.gen.ts`. Every hook on the toolchain contract is optional, so on an
 * older SDK this module would load, register, and contribute NOTHING, in
 * silence — which is why the floor is not simply the first SDK with a loader.
 */
const MIN_SDK = "1.0.6";
/** Exclusive upper bound. The range is widened deliberately, one major at a time. */
const MAX_SDK_EXCLUSIVE = "2.0.0";

/** The range as `package.json` spells it. */
export const PEER_RANGE = `>=${MIN_SDK} <${MAX_SDK_EXCLUSIVE}`;

/** `1.2.3-beta.1` → `[1, 2, 3]`; anything unparsable yields null. */
function parseVersion(v: string): [number, number, number] | null {
  const m = /^(\d+)\.(\d+)\.(\d+)/.exec(v.trim());
  return m === null ? null : [Number(m[1]), Number(m[2]), Number(m[3])];
}

function compare(a: [number, number, number], b: [number, number, number]): number {
  return a[0] - b[0] || a[1] - b[1] || a[2] - b[2];
}

/**
 * Refuse, by name and before any work, an SDK this module does not understand.
 *
 * ── Two layers ──────────────────────────────────────────────────────────────
 *
 * The SDK's loader reads this package's own `peerDependencies["@xano/sdk"]`
 * and refuses an out-of-range SDK during discovery, before this file is even
 * imported. This check is the backstop for any path that reaches a hook
 * without having gone through discovery; every hook that receives the running
 * SDK version calls it first.
 *
 * An unparsable version, or one carrying a PRERELEASE suffix, is allowed
 * through. A source checkout of the SDK reports `0.0.0-dev`, and refusing that
 * would break the `npm link` development setup. The SDK's own range test makes
 * the same trade (a prerelease is "unknown", refused only on a definite false),
 * so the two layers agree.
 */
export function assertSdkVersion(sdkVersion: string): void {
  if (sdkVersion.includes("-")) return;
  const found = parseVersion(sdkVersion);
  if (found === null) return;
  const min = parseVersion(MIN_SDK)!;
  const max = parseVersion(MAX_SDK_EXCLUSIVE)!;
  if (compare(found, min) < 0 || compare(found, max) >= 0) {
    throw new Error(
      `${PACKAGE_NAME} requires @xano/sdk ${PEER_RANGE}, but ${sdkVersion} is running. ` +
        `Upgrade @xano/sdk, or remove ${PACKAGE_NAME} from this project — no zod schemas are generated by an SDK outside that range.`,
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Reconcile
// ─────────────────────────────────────────────────────────────────────────────

/**
 * What the project gets: the config block that records the module as enabled.
 * Pure, and called on every reconcile, so it is a function of nothing.
 */
function contributes(): ProjectContributions {
  return { config: { enabled: true } };
}

/**
 * The default export the SDK's loader reads. `kind` is repeated from the
 * manifest so the two must agree.
 */
const plugin: ToolchainPlugin = {
  kind: "toolchain",
  contributes,
};

export default plugin;
